In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mlp
import matplotlib.pyplot as plt
import pickle
import sklearn
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import tree
import gradio as gr

# Data Import

In [11]:
df_X, df_y = datasets.load_iris(return_X_y=True, as_frame = True)

# Data Prep

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.30)

# Model Training

In [13]:
model = tree.DecisionTreeClassifier()

In [14]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

# Model Evaluation

In [15]:
pred = model.predict(X_test)

In [16]:
print(confusion_matrix(y_test,pred))

[[22  0  0]
 [ 0 11  2]
 [ 0  0 10]]


In [17]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      0.85      0.92        13
           2       0.83      1.00      0.91        10

    accuracy                           0.96        45
   macro avg       0.94      0.95      0.94        45
weighted avg       0.96      0.96      0.96        45



# Model UI - Gradio

In [20]:
df_X.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [28]:
#https://gradio.app/getting_started
#https://gradio.app/docs

def make_prediction(sepal_length, sepal_width, petal_length, petal_width):
    pred_array = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
    pred = model.predict(pred_array)
    if pred == 0:
        flower = "Iris Setosa"
    elif pred == 1:
        flower ="Iris Versicolour"
    elif pred == 2:
        flower = "Iris Virginica"
    return flower

iface = gr.Interface(
    fn=make_prediction, 
    inputs = ["number","number","number","number"],
    outputs = "text")
iface.launch()

Running locally at: http://127.0.0.1:7868/
To create a public link, set `share=True` in `launch()`.
Interface loading below...


(<Flask 'gradio.networking'>, 'http://127.0.0.1:7868/', None)